### ISSUE TITLE
Multi-Project build with a single gradle.properties file

### ISSUE THREAD

**Issue by grigorigoldman** [researchgate/gradle-release#102]
I have a multi-project set-up that looks something like this:

Parent build.gradle
```groovy
buildscript {

  ext {
    nexus = {
      credentials {
        username nexusBuildUserToken
        password nexusBuildPassToken
      }
      url nexusRepoURL
    }
  }

  repositories {
    maven(nexus)
  }

  dependencies {
    classpath('net.researchgate:gradle-release:2.0.2')
  }

}

allprojects {
  repositories {
    maven(nexus)
  }
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'maven'
  apply plugin: 'net.researchgate.release'

  uploadArchives {
    repositories {
      mavenDeployer {
        repository(url: nexusReleaseURL) {
          authentication(userName: nexusBuildUserToken, password: nexusBuildPassToken);
        }
        snapshotRepository(url: nexusSnapshotURL) {
          authentication(userName: nexusBuildUserToken, password: nexusBuildPassToken);
        }
      }
    }
  }

  createReleaseTag.dependsOn uploadArchives
}
```
The version number is defined in the gradle.properties file in the parent. The sub-projects don't define their own gradle.properties files.

When I run the `gradle release` command, I get the following prompt:

```bash
[path to sub-project gradle.properties] not found, create it with version = [my version number as defined in the parent gradle.properties] (Y|n) [n]
```

My question is, is it possible for all my sub-projects to inherit the version number from the parent gradle.properties or do I need to define the file in each sub-project?

Thank you.

**Comment by Michenux** [comment]
:+1:

**Comment by jamescway** [comment]
+1 same question

**Comment by danez** [comment]
Oh it seems i missed this question.

If you want to have one version for all subprojects you just need to apply the release plugin to the parent project.

The examples repository is not yet finished, but you can already have a look at the multi-project with single version there.

https://github.com/researchgate/gradle-release-examples

**Comment by jamescway** [comment]
@danez I tried to follow the example, but it still had the same problem.  I am new to gradle so it could be my lack of understanding.  Here is the relevant part of my build.gradle.  Also, if I did not put the release block inside of allprojects it didn't seem to work?
```gradle
plugins {
    id 'com.jfrog.bintray' version '1.2'
    id 'net.researchgate.release' version '2.1.2'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'scala'
    apply plugin: 'maven'
    apply plugin: 'maven-publish'
    apply plugin: 'net.researchgate.release'
    apply plugin: 'com.jfrog.bintray'

    release {
        failOnCommitNeeded = false
        failOnPublishNeeded = true
        failOnSnapshotDependencies = true
        failOnUnversionedFiles = true
        failOnUpdateNeeded = true
        revertOnFail = true

        git {
            requireBranch = 'gradle-bintray'
            pushToRemote = 'origin'
            pushToCurrentBranch = true
        }
    }
}
```

**Comment by phiroict** [comment]
I ran into the same issue, it would appear it tries to create the tag again for each sub project. Which is going to fail if your subprojects are all part of the same git project, as is mine. 
So the question is: Is there a way to run the tag only from the parent / top folder and not in all of the subprojects?

**Comment by phiroict** [comment]
Tried the multi project example, same issue: Also it omits the version property that the plugin apparently needs.

**Comment by danez** [comment]
you should not put the release plugin in the allproject or subproject part. Right now the plugin only works if you apply it to the parent.
```
plugins {
    id 'com.jfrog.bintray' version '1.2'
    id 'net.researchgate.release' version '2.1.2'
}

release {
        failOnCommitNeeded = false
        failOnPublishNeeded = true
        failOnSnapshotDependencies = true
        failOnUnversionedFiles = true
        failOnUpdateNeeded = true
        revertOnFail = true

        git {
            requireBranch = 'gradle-bintray'
            pushToRemote = 'origin'
            pushToCurrentBranch = true
        }
    }

allprojects {
    apply plugin: 'java'
    apply plugin: 'scala'
    apply plugin: 'maven'
    apply plugin: 'maven-publish'
    apply plugin: 'com.jfrog.bintray'
}
```

If you now do release it should build all your projects, but only execute the release-tasks once.

**Comment by phiroict** [comment]
Indeed it does, thanks  danez!

**Comment by jakubskopal** [comment]
Hello, I tried your example in GIT and it doesn't build the subprojects. It just does the GIT magic, but never compiles subproject1. Just cloned your repository, entered the single-version project and issued ./gradlew release. It builds just the root project and releases it, but the subproject1 is never built :(

**Comment by danez** [comment]
Thanks I will check

**Comment by scabbage** [comment]
For multi projects multi versions, I don't think the plugin will work if one of the sub project depends on the other. Is that correct?

**Comment by danez** [comment]
tracked in #144
