### ISSUE TITLE
Branch to you

### ISSUE THREAD

**Issue by stewartbryson** [researchgate/gradle-release#105]
Just a quick question. We use basic GitFlow methodology, meaning we have the develop and master branches, but don't regularly use the release branch, though we probably should. So the code we want to commit is in the develop branch, but we want it merged into master, and then a tag created.

So... does the plugin handle the merge to master, or should I do the merge to master myself, and then run the plugin against master?

Thanks.

**Comment by danez** [comment]
The plugin does not handle any merging between branches. You need to either do it yourself or write your own tasks. If you find an automated solution it would be great if you could share it for others.
