### ISSUE TITLE
checkCommitNeeded fails when there are folders as SVN externals

### ISSUE THREAD

**Issue by pstanoev** [researchgate/gradle-release#106]
On project with svn externals where the svn status command returns string like this:
```
    X   test-app\build-resources\texts.trm
X       test-app\src\main\assets\about
X       test-app\src\main\assets\offline-resources
X       test-app\src\main\assets\terms

Performing status on external item at 'test-app\src\main\assets\about':

Performing status on external item at 'test-app\src\main\assets\terms':

Performing status on external item at 'test-app\src\main\assets\offline-resources':
```
There is a java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at SvnAdapter.groovy:74:
```
switch (line?.trim()?.charAt(0)) {
```
because the output from svn status contains blank lines.

Line length should be checked before assuming there is first character.

**Comment by danez** [comment]
Was this working with a version before 2.1? Anyway I fixed the StringIndexOutOfBoundsException and also checked that it works with externals, which even after fixing the exception it showed me the externals as modified files. Going to release 2.1.1 now.

**Comment by danez** [comment]
Please let me know if it works now.

**Comment by pstanoev** [comment]
That part works but now it fails in 
checkIfUpdateNeeded, SvnAdapter.groovy:108:
``` 
switch (line?.trim()?.charAt(0)) {
```

**Comment by danez** [comment]
With the same exception? For me this part was working when I tried it.

**Comment by pstanoev** [comment]
I think it only happens if you have folders in svn externals (besides files).
Here is the output from my ```svn stat -q -u```:
```
    X         8282   test-app\build-resources\texts.trm
X                    test-app\src\main\assets\about
    X         8282   test-app\src\main\assets\app-cert-bls.p12
X                    test-app\src\main\assets\offline-resources
X                    test-app\src\main\assets\terms
Status against revision:   8308

Performing status on external item at 'test-app\src\main\assets\about':
Status against revision:   8308

```
I have SVN version 1.7.8.

```
 void checkUpdateNeeded() {
   def props = project.properties
   String svnUrl = props.releaseSvnUrl
   String svnRev = props.initialSvnRev
   String svnRemoteRev = ''
   String out = svnExec(['status', '-q', '-u'])
   def missing = []
   out.eachLine { line ->
  --> switch (line?.trim()?.charAt(0)) { 
```

**Comment by danez** [comment]
Ok I just added the same line-length-check to checkUpdateNeeded.
Could you try the latest SNAPSHOT and see if now everything works?

```
buildscript {
  repositories {
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
  }

  dependencies {
    classpath 'net.researchgate:gradle-release:2.1.2-SNAPSHOT'
  }
}
```

**Comment by pstanoev** [comment]
It is OK now.
Thanks a lot!
