### ISSUE TITLE
checkUpdateNeeded is failing while doing release

### ISSUE THREAD

**Issue by ramapotluri** [researchgate/gradle-release#108]
:release workflow:checkUpdateNeeded
Running [svn, status, -q, -u] produced an error: [svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'http://svnserver/svn/webrms/Products/workflow/branches/rms_workflow_cleanup_code'
svn: E215004: No more credentials or we tried too many times.
Authentication failed]
Running [svn, info, http://svnserver/svn/webrms/Products/workflow/branches/rms_workflow_cleanup_code] produced an error: [svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'http://svnserver/svn/webrms/Products/workflow/branches/rms_workflow_cleanup_code'
svn: E215004: No more credentials or we tried too many times.
Authentication failed]
:release workflow:checkUpdateNeeded FAILED
:release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkUpdateNeeded'.
> Local revision (12766) does not match remote (), local revision is used in tag creation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
Please suggest some solution to me. Thanks.

**Comment by danez** [comment]
This means that there are no credentials stored on this system for your svn server. Normally you should be asked about the credentials when run from terminal. Maybe it is not working with the gradle 2.4 daemon.

**Comment by ramapotluri** [comment]
from terminal its working fine. I am getting this error when I run release -Pgradle.release.useAutomaticVersion=true from jenkins

**Comment by danez** [comment]
Then you either need to store the credentials on your jenkins machine, or supply the credentials on the command line:
```gradle release -Pgradle.release.useAutomaticVersion=true -Prelease.svn.username=username -Prelease.svn.password=secret```

**Comment by ramapotluri** [comment]
how do we store credentials on jenkins machine?

**Comment by danez** [comment]
That's out of the scope here. The easiest solution is probably enabling plaintext password storage for svn  and running a svn command once by hand on that machine. Just search for it.

**Comment by ramapotluri** [comment]
thanks. now its working by providing username and password as gradle params.
