### ISSUE TITLE
No such field error for release configuration

### ISSUE THREAD

**Issue by skuppa** [researchgate/gradle-release#109]
I am trying to integrate `gradle-release` plugin into my project and I am getting error that "No such field" though this method is part of class.  I am able to reproduce the problem by adding the plugin into sample project from gradle distribution.  

I have checked in the sample repo `https://github.com/skuppa/gradle-release-test`, you can try out and let me know, is there any configuration error or is it due to some bug 

Error stack
```
$ ./gradlew release
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kuppas/tmp/multiproject/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'multiproject'.
> No such field: simpleName for class: net.researchgate.release.GitAdapter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Thanks,
Kuppa

**Comment by danez** [comment]
You need to either add an import for the GitAdapter class to your build.gradle
```import net.researchgate.release.GitAdapter```
or change this line from the configuration to:
```scmAdapter =[net.researchgate.release.GitAdapter]```
or remove this line all together.

**Comment by skuppa** [comment]
Thank you very much for the quick response.  It works great now :+1:   Sorry for my stupid mistake :(
