### ISSUE TITLE
providing username and password for git

### ISSUE THREAD

**Issue by SylvainVISSIERE-GUERINET** [researchgate/gradle-release#112]
Hi,

i'm looking for some gradle plugin to make release with git.

i tried different plugins, yours works with my git server but i have to use git credential helpers to store my credentials.

is it possible to add credential parameter (like the ones for svn) for git?

**Comment by danez** [comment]
Git works in a different way than svn. There is no way in git to provide username and password on the command line. In git the preferred way is using [ssh keys][2] and ssh protocol for accessing servers. If this is not possible, then you would need to find a way on your own as the git commands do not support credentials as parameters. This answer on [stackoverflow][1] sums up all the possibilities. 
Maybe there is a even better way, but I'm not aware of.

[1]: http://stackoverflow.com/a/11506234/3739237
[2]: https://help.github.com/articles/generating-ssh-keys/

**Comment by SylvainVISSIERE-GUERINET** [comment]
ok, that's what i'm doing for now. thanks.
