### ISSUE TITLE
gradle_empty_settings error while calling uploadArchive

### ISSUE THREAD

**Issue by vishalvsh1** [researchgate/gradle-release#115]
Under custom release steps upload archive task does not work as per suggestion.
**_afterReleaseBuild.dependsOn uploadArchives_**

When uploadArchive executes before afterReleaseBuild task, it is not able to find the artifacts to upload and throws following error 

>Error reading settings file '/tmp/gradle_empty_settings6948127724047432425.xml' - ignoring. Error was: /tmp/gradle_empty_settings6948127724047432425.xml (No such file or directory)

I feel best way to call uploadArchive is 
**_createReleaseTag.dependsOn allprojects.uploadArchives_**

The same way it was mentioned with 1.x release. This still works for 2.x.
I have tested it in my system.

**Comment by danez** [comment]
What is the complete commandline-output, when this error occurs?

The change to ```afterReleaseBuild.dependsOn uploadArchives``` was made so the version of the build is set correctly. It might be wrong when using ```createReleaseTag.dependsOn allprojects.uploadArchives```.

**Comment by vishalvsh1** [comment]
Hi Danez,
  Looks like above issue was only happening with gradle v 2.0/2.1. I checked with version 2.4. It's working as per your document.

**Comment by danez** [comment]
I will test gradle 2.1 and 2.0

**Comment by danez** [comment]
I could not reproduce and after searching on the net it seems this can happen if the maven plugin is applied to a project that is not producing an artifact.
If it ever happens again please create a sample repo.
