### ISSUE TITLE
no spaces in gradle.properties allowed?

### ISSUE THREAD

**Issue by simonsilvalauinger** [researchgate/gradle-release#120]
I had a problem defining my project version in gradle.properties. I used spaces between 'version' '=' and the version number (mean ``` version = '0.1.0-SNAPSHOT' ´´´). The plugin doesn't accept this correct property file. After removing the spaces it worked.
Is it possible to let the plugin read the properties file correct?

Regards,
Simon

**Comment by danez** [comment]
Thanks for your report, this will be fixed in the next version.
