### ISSUE TITLE
line: buildTasks = ['build']

### ISSUE THREAD

**Issue by pizi6** [researchgate/gradle-release#122]
line: buildTasks = ['build']
No such property: buildTasks for class: net.researchgate.release.ReleaseExtension_Decorated

**Comment by danez** [comment]
Sorry the README is already updated for version 2.2.0. In the latest stable version 2.1.x this feature is not available.

**Comment by pizi6** [comment]
Sorry, I can not look for README version 2.2.0. Where is it. Can you give me a link? :+1:
