### ISSUE TITLE
allow to provide git username & password 

### ISSUE THREAD

**Issue by dodgex** [researchgate/gradle-release#124]
Hello,

my git repository is only available via https and requires username & password. With the current state of the plugin i can not run a release on jenkins as i can not provide a git username and password as for svn.

while i haven't found a good way to provide credentials to the `git` command, i know how such an option could be added when using JGit to do the git related work.

**Comment by danez** [comment]
There is no plan to use JGit, you need to find a solution outside of the release plugin. The git cli command does not support providing username & password.
