### ISSUE TITLE
Authentication Failed while updating in Jenkins 

### ISSUE THREAD

**Issue by sandeeprao** [researchgate/gradle-release#127]
I am getting authentication failed error when trying to run the gradle release task from the jenkins. Is this reletaed to svn version issue ? This error only occuring when running the gradle release task. I have replacted URL in with actual url.  

:workspace:checkUpdateNeeded
Running [svn, status, -q, -u] produced an error: [svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'ACTUAL_URL'
svn: E215004: No more credentials or we tried too many times.
Authentication failed]
Running [svn, info, ACTUAL_URL'] produced an error: [svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'ACTUAL_URL'
svn: E215004: No more credentials or we tried too many times.
Authentication failed]

**Comment by danez** [comment]
You somewhoe need to supply credentials to svn, either by using a credential-helper in the operating system, or by using the options for username and password in the gradle-release configurations. See https://github.com/researchgate/gradle-release/blob/master/CHANGELOG.md#new-features-1
