### ISSUE TITLE
Release plugin continues to execute after preTagCommit command fails

### ISSUE THREAD

**Issue by grigorigoldman** [researchgate/gradle-release#128]
We've noticed that when running `gradle release` command and it fails when executing the preTagCommit task:

```
28-Aug-2015 15:36:57	Running [git, commit, -a, -m, [Gradle Release Plugin] - pre tag commit:  '1.0.10'.] produced an error: [*** Please tell me who you are.
28-Aug-2015 15:36:57	
28-Aug-2015 15:36:57	Run
28-Aug-2015 15:36:57	
28-Aug-2015 15:36:57	  git config --global user.email "you@example.com"
28-Aug-2015 15:36:57	  git config --global user.name "Your Name"
28-Aug-2015 15:36:57	
28-Aug-2015 15:36:57	to set your account's default identity.
28-Aug-2015 15:36:57	Omit --global to set the identity only in this repository.
28-Aug-2015 15:36:57	
28-Aug-2015 15:36:57	fatal: unable to auto-detect email address (got 'xxx@yyy.(none)')]
```

The problem is, the job Bamboo job continues to run, which causes issues because we publish our artefact to Nexus but then subsequently fail to up the version (for the same reason). We then can't rerun the failed job because we're set restrictions on Nexus to disallow artefact overwrites. Looking at the `Executor.exec` method (line 50), it should be catching this and throw exception but it doesn't seem to be happening.

**Comment by danez** [comment]
Thanks, should be fixed in next release
