### ISSUE TITLE
Could not determine root SVN url

### ISSUE THREAD

**Issue by sandeeprao** [researchgate/gradle-release#131]
Hi, 

I am getting the following error when trying to run release for a multimodule project from command line 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectB:initScmAdapter'.
> Could not determine root SVN url or revision.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
Can you explain me in more detail how i can solve this ?

**Comment by danez** [comment]
How did u setup the release plugin?

**Comment by naugler** [comment]
Careful, I received this error because my repository TRUNK, BRANCHES, TAGS were all capitalized. The plugin is looking for

    URL:\s(.*?)(\/(trunk|branches|tags).*?)

 If this is your problem, the issue has been resolved and will be included in the next release of the plugin.

**Comment by sandeeprao** [comment]
My branches are not capitalized.  I have added this to my sub projects  and i am running the release task 

plugins {
 
  id 'net.researchgate.release' version '2.2.0'
  }

**Comment by danez** [comment]
Adding the release plugin to the subprojects is not yet supported.
From the README:
> Support for multi-project builds isn't complete, but will work given some assumptions. The gradle-release plugin assumes and expects the following:
> 
> Only the root|parent project is applying the plugin
> Only one version is used for root and sub projects
> Only one version control system is used by both root and sub projects

**Comment by danez** [comment]
tracked in #144
