### ISSUE TITLE
-PnewVersion doesn't seem to work

### ISSUE THREAD

**Issue by shintasmith** [researchgate/gradle-release#134]
We use ```com.github.townsfolk:gradle-release:1.2``` and gradle 2.2. Our gradle command is like this:
```
$ /var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/gradle-2.2/bin/gradle  -DnewVersion=1.3.0-SNAPSHOT -Prelease.useAutomaticVersion=true clean release
```
But the plugin doesn't seem to take the newVersion parameter:
```
:nabu:createReleaseTag
:nabu:updateVersion

??> Enter the next version (current one released as [1.2.0]): [1.2.1-SNAPSHOT]  (WAITING FOR INPUT BELOW)

:nabu:commitNewVersion
```
At the end we ended up with 1.2.1-SNAPSHOT.

How can I pass in the next dev snapshot version?

**Comment by danez** [comment]
`com.github.townsfolk:gradle-release:1.2` is very outdated. You should consider updating to the latest version `net.researchgate:gradle-release:2.2.2`.
The feature you want to use was added in 2.0 and is not available in 1.2.

**Comment by shintasmith** [comment]
Unfortunately, the version 2.2.2 gradle-release doesn't work well with our multi-projects build. We could not get it to work. I can post a separate issue for the multi-project build.

**Comment by danez** [comment]
Yes please do so.
