### ISSUE TITLE
New Version Update

### ISSUE THREAD

**Issue by ramapotluri** [researchgate/gradle-release#136]
I have jenkins release build, which releases the version 3.6.1.700. After that I need to have a new version as 3.6.1.800-SNAPSHOT instead of 3.6.1.701. That means my next release version will be 3.6.1.800. This should happen automatically instead of interactively. Is it possible thru this plugin.

**Comment by danez** [comment]
The most elegant version to do this is probably to define a custom `versionPatterns` (no waranty for the example below, but if you are fit with regexes it should be no problem to understand what I tried.)
```
release {
    versionPatterns = [
        /(\d00)([^\d]*$)/: { Matcher m, Project p -> m.replaceAll("${(m[0][1] as int) + 100}${m[0][2]}") }
    ]
}
```
and then use this command line in jenkins
```
    gradle release -Prelease.useAutomaticVersion=true
```

**Comment by ramapotluri** [comment]
Thank You. That did work.
