### ISSUE TITLE
Cannot upload integration with "maven-publish" plugin

### ISSUE THREAD

**Issue by hatavan83** [researchgate/gradle-release#137]
How can I integration with "maven-publish" plugin to publish release version to maven before commit to svn ? I already try to add "afterReleaseBuild.dependsOn publishing" or  "afterReleaseBuild.dependsOn publish" to build.gradle file, but it is not success

**Comment by danez** [comment]
The second one is the correct one. Do you get an error? Is it working when you call ```gradle publish``` on the command line?

**Comment by hatavan83** [comment]
I can call gradle publish, but cannot customize with afterReleaseBuild task, error "cannot found property publish" was thrown.
Addition, I add custome task to delete some files and add some files with afterReleaseBuild, but these files cannot commit to svn tag release, how can I do it with afterReleaseBuild task

**Comment by danez** [comment]
Then try ```afterReleaseBuild.dependsOn project.tasks.publish```, if it still is not working pls post your build script.

**Comment by hatavan83** [comment]
Cannot successfully, this is my build script 
buildscript {
    repositories {
        maven {
            url "http://clojars.org/repo"
        }
    }

    dependencies {
        classpath "org.apache.maven:maven-artifact:2.2.1"
        classpath "org.apache.avro:avro-compiler:1.7.6"
        classpath "org.clojars.miguno:avro-gradle-plugin:1.7.6"
    }
}

plugins {
  id "net.researchgate.release" version "2.2.2"
}

apply plugin: "base"

description = "Demo project Big Data Reporting Project"

ext{
	deploymentDir = "build/deployment"
}

allprojects {
	apply plugin: "jacoco"
	apply plugin: "java"
	apply plugin: "eclipse"
	
	group = "com.bigdata.demo"

	sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
	
	repositories {
		mavenLocal()		
		mavenCentral()
		maven { url "http://repo.spring.io/libs-release" }
		maven { url "https://repository.cloudera.com/artifactory/cloudera-repos" }
	}	
}

subprojects {	
	apply plugin: "maven-publish"

	dependencies {
		compile "org.slf4j:jcl-over-slf4j:$slf4jVersion"
	    compile "org.slf4j:slf4j-log4j12:$slf4jVersion"
	    compile "org.slf4j:slf4j-api:$slf4jVersion"
	    compile "log4j:log4j:$log4jVersion"
	    testCompile "junit:junit:$junitVersion"
	    testCompile "org.mockito:mockito-core:$mockitoVersion"
		testCompile "org.powermock:powermock-core:$powermockVersion"
		testCompile "org.powermock:powermock-api-mockito:$powermockVersion"
		testCompile "org.powermock:powermock-module-junit4:$powermockVersion"
	}
	
	jacocoTestReport {
		reports {
			html.enabled = true
			xml.enabled = true
			csv.enabled = true
		}
	}	
	
	publishing {
	
	    publications {
	        mavenJava(MavenPublication) {
	            from components.java
	            artifact sourceJar {
	                classifier "sources"
	            }
	        }
	    }
	    
	    repositories {
	        maven {
	     		url "http://localhost:8180/nexus/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases'}"          		
	        }
	    }
	}
	
	task sourceJar(type: Jar) {
    	from sourceSets.main.allJava
	}	
}

release {
    failOnCommitNeeded = true
    failOnPublishNeeded = true
    failOnSnapshotDependencies = true
    failOnUnversionedFiles = true
    failOnUpdateNeeded = true
    revertOnFail = true
    preCommitText = ""
    preTagCommitMessage = "[Gradle Release Plugin] - pre tag commit: "
    tagCommitMessage = "[Gradle Release Plugin] - creating tag: "
    newVersionCommitMessage = "[Gradle Release Plugin] - new version commit: "
    tagTemplate = "${version}"
    versionPropertyFile = "gradle.properties"
    
    scmAdapters = [       
        net.researchgate.release.SvnAdapter       
    ]   
}

afterReleaseBuild.dependsOn "prepareDeploymentArchives"
afterReleaseBuild.dependsOn project.tasks.publish

task prepareDeploymentArchives(type: Tar, dependsOn: ["copyDeploymentArchivesToLib"]){
	from deploymentDir
	baseName = "bigdata-reporting"
	version = null
	extension = "tar.gz"
	compression = Compression.GZIP
	destinationDir = file("deployment")
}

task copyDeploymentArchivesToLib(type: Copy, dependsOn: ["deleteDeploymentArchives"]) {
	from("data"){
		into "data"
	}
	from("scripts"){
		into "scripts"
	}
	from("oozie"){
		into "oozie"
	}
	from(subprojects.jar){
		into "oozie/lib"
	}
	into project.file("${deploymentDir}")
}

task deleteDeploymentArchives(type: Delete){	
	delete fileTree(dir: "${deploymentDir}", include: "**/*")
}

**Comment by hatavan83** [comment]
It is ok now, thank for your support
