### ISSUE TITLE
Sub modules will not get uploaded via "depends on" custom release step

### ISSUE THREAD

**Issue by vishalvsh1** [researchgate/gradle-release#138]
Hi,
    Just want to highlight one point here, Its not a bug or anything. It is just a gradle feature (or anything).

Would be great if you can add following in the documentation under multi-module project.

<h3>Custom release steps  for MultiModule projects</h3>

In case of multi module builds following change needs to be done for submodules artifacts upload.
   `afterReleaseBuild.dependsOn { uploadArchives }`

otherwise without this { } submodules build will throw following error.

`Could not find property ‘uploadArchives’ on project ‘:submodule’.`

I personally faced this issue, so thought of requesting you to add this portion in the document which can help others.

**Comment by ianpojman** [comment]
I ran into this same issue and I saw also this raised for it: https://github.com/researchgate/gradle-release/issues/168

**Comment by dazza5000** [comment]
I am still struggling with getting uploadArchives working on multi-module projects with Gradle 5.2. Does anyone have a good solution for this? This is what we were trying:

```
afterEvaluate {
    subprojects { subproject ->
        subproject.tasks.withType(Upload).configureEach { task ->
            print "adding the following task: " + task.name + " to the following subproject: " + subproject.name
            afterReleaseBuild.dependsOn task
        }
    }
}

```

**Comment by Hillkorn** [comment]
What is the error you get?

**Comment by dazza5000** [comment]
I dont get an error, but the upload tasks dont upload the artifacts in the sub-projects. I found a solution that works, but it is more manual. Will post it shortly.

**Comment by Hillkorn** [comment]
The task is called but nothing is uploaded you mean?

**Comment by dazza5000** [comment]
If I specify the afterReleaseBuild uploads like this, the uploads work:

```
afterReleaseBuild.dependsOn (':project1:uploadArchives',
':project2:uploadArchives')

```

**Comment by Hillkorn** [comment]
We do it similar and this works well.
```
project.tasks.afterReleaseBuild.dependsOn project.getSubprojects().collect({
    it.getTasks().getByName("uploadArchives")
})
```

**Comment by dazza5000** [comment]
Will try that - thank you! <3
