### ISSUE TITLE
Using "tagTemplate" property confuses SNAPSHOT version

### ISSUE THREAD

**Issue by tombc** [researchgate/gradle-release#139]
Hello,

I am releasing a library having version 2.5-SNAPSHOT.

When I do NOT specify a tagTemplate property, everything works fine. The SCM tag is created with name "2.5" and the commit message for the new version is "[Gradle Release Plugin] - new version commit:  '2.6-SNAPSHOT'."

However, when setting the tagTemplate property to  "$name-$version" things become weird:
- the SCM tag is created as **"2.5-SNAPSHOT"** (instead of "2.5")
- the commit message for the new version is **"[Gradle Release Plugin] - new version commit:  '2.5-SNAPSHOT'."** (instead of "2.6-SNAPSHOT")

Could you please have a look?

**Comment by danez** [comment]
Probably you are using double quotes in your gradle file, which means the variables get replaces when the file is parsed. To fix it use single quotes.

**Comment by tombc** [comment]
Oops, yes, great! Single quotes work. Thanks a lot.

**Comment by patflynn** [comment]
Just FYI your usage doc uses double quotes for the tagTemplate example:

> Example: "$name-$version" will result in "myproject-1.1.0"

**Comment by danez** [comment]
Thanks I made it more clear.

**Comment by craigtmoore** [comment]
Maybe we should include a note about this in the documentation.
