### ISSUE TITLE
Error: No such device or address

### ISSUE THREAD

**Issue by chenrui333** [researchgate/gradle-release#141]
Hi All,

When I tried to setup with Jenkins to do the release task, I found the following error.

cmd line option is "./gradlew --refresh-dependencies --debug uploadArchives release", it seems the username and password are not recognized, do I need to do separate setup for the workspace of this project?

The SCM polling is working fine.

Thanks,
Rui

09:22:38.353 [ERROR] [org.gradle.BuildExceptionReporter] 
09:22:38.357 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:22:38.359 [ERROR] [org.gradle.BuildExceptionReporter] 
09:22:38.359 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
09:22:38.359 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':checkUpdateNeeded'.
09:22:38.359 [ERROR] [org.gradle.BuildExceptionReporter] > Failed to run [git remote update] - [Fetching origin
09:22:38.359 [ERROR] [org.gradle.BuildExceptionReporter]   ][fatal: could not read Username for 'https://git.domain': No such device or address

**Comment by chenrui333** [comment]
Here is my release task config
release {
    failOnCommitNeeded = false
    failOnPublishNeeded = false
    failOnSnapshotDependencies = true
    failOnUnversionedFiles = false
    failOnUpdateNeeded = true
    revertOnFail = true

    git {
        requireBranch = ''
        pushToRemote = 'origin'
        pushToCurrentBranch = false
    }
}

**Comment by danez** [comment]
It seems your ci machine has no access to your git repository. You need to setup proper credentials on the machine where jenkins runs, before running the release plugin.

**Comment by chenrui333** [comment]
@danez 
OK, I will try tomorrow. Thanks.

**Comment by diegobmd** [comment]
Anybody solve this? I use on jenkins ci too and have same problem. It clone normally but when will check had a same message above
On my local machine works fine

**Comment by chenrui333** [comment]
@diegobmd We setup SSH key and configure Jenkins to the key to access `git@hostname:user/repo.git`. and it works for us.
