### ISSUE TITLE
Getting > Could not find method git() for arguments [build_734r8de0xhabv67mcbshcsbho$_run_closure9_closure26@65c88d95] on root project 

### ISSUE THREAD

**Issue by ali1112** [researchgate/gradle-release#143]
Hi,
i am getting following error while running gradle release:

> Could not find method git() for arguments [build_734r8de0xhabv67mcbshcsbho$_run_closure9_closure26@65c88d95] on root project 

Can somebody please help.

Here is my release target in build.gradle:

release {
    failOnCommitNeeded = true
    failOnPublishNeeded = true
    failOnSnapshotDependencies = true
    failOnUnversionedFiles = true
    failOnUpdateNeeded = true
    revertOnFail = true
    preCommitText = ''
    preTagCommitMessage = '[Release] - pre tag commit: '
    tagCommitMessage = '[Release] - creating tag: '
    newVersionCommitMessage = '[Release] - new version commit: '
    tagTemplate = '${version}'
    versionPropertyFile = 'gradle.properties'
    versionProperties = []
    scmAdapters = [GitAdapter]

    git {
        requireBranch = 'master'
        pushToRemote = 'origin'
        pushToCurrentBranch = false
    }
}

**Comment by danez** [comment]
You need to use the full qualified name of the Adapter, or import it. That is probably the problem.
```
scmAdapters = [net.researchgate.release.GitAdapter]
```

**Comment by ali1112** [comment]
Thanks.
It worked
