### ISSUE TITLE
NullPointerException during execution of task 'checkUpdateNeeded'

### ISSUE THREAD

**Issue by IVU-chl** [researchgate/gradle-release#145]
Hi,

I use the release plugin in a Jenkins Project and SVN and get a NullPointerException during task 'checkUpdateNeeded'.

- Versions:
Jenkins: 1.625.1
Plugin: 2.3.0
Gradle: 2.8 (2.7)
SVN: 1.6.17

- Configuration:
plugins {
(...)
    id 'net.researchgate.release' version '2.3.0'
}
release {
    includeProjectNameInTag = true
    failOnUnversionedFiles = false
	failOnCommitNeeded = false
    failOnUpdateNeeded = false
    scmAdapters = [
        net.researchgate.release.SvnAdapter
    ]
    svn {
        username = '***'
        password = '***'
    }
}

- Switches:
--no-daemon -Prelease.useAutomaticVersion=true

- LOG:
13:37:15.364 [INFO] [org.gradle.api.Project] Running [svn, --non-interactive, --no-auth-cache, --username, ***, --password, ***, info, null] in [/home/jenkins-slave/workspace/ivu.pto.commons.annotations_release]
13:37:15.366 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':checkUpdateNeeded'
13:37:15.366 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :pto-commons-annotations:checkUpdateNeeded FAILED
13:37:15.374 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :checkUpdateNeeded (Thread[main,5,main]) completed. Took 0.311 secs.
13:37:15.375 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 0.678 secs, idle: 0.014 secs
13:37:15.387 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolved configuration cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
13:37:15.388 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
13:37:15.389 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.001 secs
13:37:15.389 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 1, cache instances: 1, modules served from cache: 0, artifacts: 0
13:37:15.393 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
13:37:15.393 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).
13:37:15.394 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':release'
13:37:15.395 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :release FAILED
13:37:15.400 [ERROR] [org.gradle.api.Project] Release process failed, reverting back any changes made by Release Plugin.
13:37:15.404 [INFO] [org.gradle.api.Project] Running [svn, --non-interactive, --no-auth-cache, --username, ***, --password, ***, revert, gradle.properties] in [/home/jenkins-slave/workspace/ivu.pto.commons.annotations_release]
13:37:15.418 [INFO] [org.gradle.api.Project] Running [svn, --non-interactive, --no-auth-cache, --username, ***, --password, ***, revert, gradle.properties] produced output: []
13:37:15.424 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :release (Thread[main,5,main]) completed. Took 1.576 secs.
13:37:15.425 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 1.593 secs, idle: 0.003 secs
13:37:15.429 [ERROR] [org.gradle.BuildExceptionReporter] 
13:37:15.431 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
13:37:15.431 [ERROR] [org.gradle.BuildExceptionReporter] 
13:37:15.432 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
13:37:15.432 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':checkUpdateNeeded'.
13:37:15.433 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException (no error message)
13:37:15.434 [ERROR] [org.gradle.BuildExceptionReporter] 
13:37:15.434 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
13:37:15.436 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkUpdateNeeded'.
13:37:15.436 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
13:37:15.437 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
13:37:15.437 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
13:37:15.438 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
13:37:15.438 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
13:37:15.439 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
13:37:15.439 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
13:37:15.439 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)

Thanks!

Christoph

**Comment by danez** [comment]
Ohhh, yes I can confirm that, will fix it in a minute.

**Comment by danez** [comment]
I create a new bugfix release as soon as I'm back to my home computer.

**Comment by arindell** [comment]
Wow, really fast!

**Comment by IVU-chl** [comment]
Thanks a lot!
