### ISSUE TITLE
SVN: Local revision (correct-revision) does not match remote (), local revision is used in tag creation.

### ISSUE THREAD

**Issue by Myllyenko** [researchgate/gradle-release#146]
I migrated from gradle-release 2.2.2 to 2.3.1 with SVN and get the following exception during release:
Local revision (correct-revision) does not match remote **()**, local revision is used in tag creation.

I've took a quick look to a source code and it semms like the ```svnRemoteVariable``` is
[initialised](https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/SvnAdapter.groovy#L101) but then isn't changed before check.

**Comment by danez** [comment]
Thanks for reporting, indeed there was something wrong, will be fixed in 2.3.2
