### ISSUE TITLE
Execution failed for task ':initScmAdapter'

### ISSUE THREAD

**Issue by espinraf** [researchgate/gradle-release#150]
Hi,

I getting a error when I try to release from Jenkins.

:release
:workspace:createScmAdapter
:workspace:initScmAdapter FAILED
:release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initScmAdapter'.
> Current Git branch is "(detached from 98e8ec6)" and not "master".

I don't know what is wrong, It is WORKING PERFECT from a Shell. but Not inside Jenkins.

SOFTWARE
Mac OS -  El Capitan
gradle -   2.8
tomcat -  7.0.59
Jenkins - 1.6

I have my own gradle plugin which includes Release Plugin.

tell me if you need more info, Thanks

**Comment by danez** [comment]
That sounds to me as of jenkins is not checking out master. I'm not sure what your configuration looks like, I think you need to make sure that the branch you want to release from is checked out. This is our configuration which works fine.
![bildschirmfoto 2015-11-09 um 12 00 22](https://cloud.githubusercontent.com/assets/231804/11032140/999407e2-86d9-11e5-83d6-f12eef50d800.png)

**Comment by espinraf** [comment]
It Works now !!
Thanks !!!
It was missing in my configuration, the Additional Behaviours - Checkout to specific local branch.
/Rafael

**Comment by Dipanshu007** [comment]
Hello, I am also facing the same problem when using this plugin with Bamboo. Can anyone suggests the configuration for Bamboo ?
