### ISSUE TITLE
Parametrized Release Version Not Included

### ISSUE THREAD

**Issue by FuadBalashov** [researchgate/gradle-release#153]
According to the documentation it should be possible to specify a release version and a release version:

> You can do this by setting the release.useAutomaticVersion property on the command line, or in Jenkins when you execute gradle. The version to release and the next version can be optionally defined using the properties release.releaseVersion and release.newVersion.
```
gradle release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=1.0.0 -Prelease.newVersion=1.1.0-SNAPSHOT
```

However, when I run the release plugin locally, the releaseVersion and newVersion seem to be ignored:
```
./gradlew release -Prelease.releaseVersion=2.9.0 -Prelease.newVersion=2.9.1-SNAPSHOT -x checkUpdateNeeded
```
the gradle version is 2.5 and the android plugin version is 1.3.1

**Comment by danez** [comment]
I assume you use the latest version of this plugin? 2.3.3?
I can't reproduce that here with the same commandline.
Which java version do you have and which operating system?

**Comment by FuadBalashov** [comment]
Thank you for the prompt reply.
I am actually using 2.2.2. Ill try out 2.3.3 today and get back to you. I am on OSX Yosemite with Java 1.7.0_76

**Comment by danez** [comment]
If you want to stay at 2.2 you can use the parameters described here:
https://github.com/researchgate/gradle-release/tree/2.2#working-in-continuous-integration

**Comment by FuadBalashov** [comment]
Ahh, okay that would make sense! Ill check out those arguments in the link with 2.2 today to confirm.

I tried out the original parameters with 2.3.3 and it seems like the plugin is successfully taking in the version parameters.
