### ISSUE TITLE
tag commit message use preTagCommitMessage instead of tagCommitMessage

### ISSUE THREAD

**Issue by otis78** [researchgate/gradle-release#158]
To reproduce:
I'm using gradle-release:2.3.4 with git. Then I set:
*tagCommitMessage = '[Gradle Release Plugin] - creating tag:  xxxxx'*

but after a complete release and I check commit message for a release tag I find:
*[Gradle Release Plugin] - pre tag commit:  xxxxx.*

----
I think because in your source on row 184 of:
*src/main/groovy/net/researchgate/release/ReleasePlugin.groovy*
in method commitTag() preCommitText are used instead of tagCommitMessage.

message = "${extension.preCommitText} ${message}"

**Comment by danez** [comment]
tagCommitMessage is used for the tag, try executing `git tag <your tag>` and you will see it.
preCommitText is a message that is prepended to all messages.

If you want to change the commit messages in git then you have to options:

`preTagCommitMessage `: If you use SNAPSHOT versions, then this is the message for the first commit with the SNAPSHOT being removed from the version.
`newVersionCommitMessage `: This is the message for the commit with the new dev version (SNAPSHOT)

**Comment by otis78** [comment]
Thanks for the explanation, and thanks in general for a good job with this plugin
