### ISSUE TITLE
initScmAdapter fails for Mercurial clones of a local folder

### ISSUE THREAD

**Issue by swpalmer** [researchgate/gradle-release#162]
> hg clone Server Server_Test
> cd Server_Test
> gradle release

:Server_Test:Server:createScmAdapter
:Server_Test:Server:initScmAdapter
Running [svn, info] produced an error: [svn: warning: W155010: The node '/Users/scott/dev/Project/Server_Test' was not found.

svn: E200009: Could not display info for all targets because some targets don't exist]
:Server_Test:Server:initScmAdapter FAILED
:Server:release FAILED

Note the attempt to use Subversion.  There is no .svn folder, and there is a .hg folder, so why that happened I can only guess.

Forcing the SCM to Mercurial with:

release {
  scmAdapters = [ net.researchgate.release.HgAdapter ]
}

works to get past this issue.

**Comment by danez** [comment]
Are you sure there is no `.svn` folder in your directory or one of the parent directories?

**Comment by swpalmer** [comment]
Yes... I did find one further up the folder hierarchy. It shouldn't have been there anymore either actually, so I can fix this for my case, but I guess the general problem remains.
