### ISSUE TITLE
"No such field" when setting properties for SCM adapters via extension

### ISSUE THREAD

**Issue by Myllyenko** [researchgate/gradle-release#164]
I'm unsuccessfully trying to enable the ```svn.pinExternals``` parameter. I've tried both ```release.svn.pinExternals = true``` and
```
release
{
	svn.pinExternals = true
}
```

The result is the same: ```No such field: pinExternals for class: net.researchgate.release.SvnAdapter```

The interesting thing is when I execute these statements:
```
println release.svn.class.name
println release.svn.pinExternals
```
it first prints ```net.researchgate.release.SvnAdapter$SvnConfig``` but then fails to find ```pinExternals``` in the class ```SvnAdapter```.

I've also tried full configuration from the main page and it has produced the similar error:
```
No such field: commitVersionFileOnly for class: net.researchgate.release.GitAdapter``` (as Git is configured first).

**Comment by danez** [comment]
`pinExternals` is not yet released

**Comment by Myllyenko** [comment]
:)

Thanks. Please mark unreleased features in "all possible configuration options and its default values" at the main page
