### ISSUE TITLE
Not generating / uploading pom.xml

### ISSUE THREAD

**Issue by nykolaslima** [researchgate/gradle-release#165]
When deploying an artifact we want both to be deployed, the jar and the pom.xml in order to projects who use it know what dependencies it needs.

gradle-release isn't doing this. how can I configure it?

**Comment by danez** [comment]
The gradle-release plugin isn't doing any deploying at all. All it does is managing the release version and some dependency stuff. 
Dependening on what you use to deploy your artifacts you might need to look into the publish or the java plugin.
