### ISSUE TITLE
How to provide Git credentials in release taks

### ISSUE THREAD

**Issue by narkesn** [researchgate/gradle-release#176]
I am following error message in jenkins : 

Execution failed for task ':checkUpdateNeeded'.

> Failed to run [git remote update] - [Fetching origin
>   ][error: The requested URL returned error: 401 Unauthorized while accessing 

In local its working fine. So is there anyway to set credentials for git so that jenkins job won't fail.

Thanks,
Sidhu

**Comment by scrain** [comment]
We have been struggling with the same issue as it seems the Jenkins workspace is left with local repo that is detached from the remote.  As a work around we ended up executing some direct git commands as a build step that gets the local repository re-connected to the remote.  

```
git remote remove origin
git remote add origin https://%GIT_USERNAME%:%GIT_PASSWORD%@your.git.host/path/to/repo.git
git fetch
git branch --set-upstream-to=origin/master master
```
