### ISSUE TITLE
afterReleaseBuild task does not work with artifactoryPublish plugin

### ISSUE THREAD

**Issue by sridhar1982** [researchgate/gradle-release#190]
I am trying to publish my artifact (jar) to artifactory using `artifactory publish plugin`. I am using [gradle release plugin][1] to manage versions. 

when I run `./gradlew clean release -Prelease.useAutomaticVersion=true`, I do not see the artifact published to artifactory

but when I run `./gradlew artifactoryPublish`, I see the artifact published.

I have configured the following so that artifactoryPublish task is run after release

`afterReleaseBuild.dependsOn artifactoryPublish`

**build.gradle**

    buildscript {
    	ext {
            springBootVersion = '1.4.0.RELEASE'
            javaVersion = '1.8'
            springVersion = '4.1.6.RELEASE'
    	}
        repositories {
            mavenLocal()
            maven { url 'fooboar/artifactory/' }
            mavenCentral()
            jcenter()
        }
    	dependencies {
    		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
            classpath "org.jfrog.buildinfo:build-info-extractor-gradle:+" 
            classpath 'net.researchgate:gradle-release:2.+'
    	}
    }
    
    allprojects {
        apply plugin: "com.jfrog.artifactory"
        apply plugin: 'net.researchgate.release'
    }
    
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'spring-boot'
    apply plugin: 'idea'
    apply plugin: 'maven'
    apply plugin: 'maven-publish'
    
    
    group 'com.company.foo.services'
    
    springBoot {
        executable = true
    }
    
    jar {
    	baseName = 'my-awesome-app'
    }
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    
    repositories {
        mavenLocal()
        maven { url 'foobar/artifactory/repo/' }
    	mavenCentral()
    }
    
    
    dependencies {
    	compile "org.springframework.boot:spring-boot-starter:${springBootVersion}"
    	compile "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
        compile "org.springframework.boot:spring-boot-starter-jdbc:${springBootVersion}"
    }
    
    artifactory {
        contextUrl = "http://foobar/artifactory"
        publish {
            repository {
                repoKey = 'sandbox'
                maven = true
                username = "awesome"
                password = "dfaertewdeec"
            }
            defaults {
                publications ('mavenJava')
            }
        }
        resolve {
            repository {
                repoKey = 'sandbox'
                maven = true
                username = 'awesome'
                password = '3235325325'
            }
        }
    }
    
    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }
    
    release {
        git {
            requireBranch = 'master'
        }
    }
    
    afterReleaseBuild.dependsOn artifactoryPublish

  [1]: https://github.com/researchgate/gradle-release

**Comment by Hillkorn** [comment]
The setup looks good to me. I'll try to reproduce it and write back.
Could you please add the gradle version you use and is the version of the wrapper the same?

**Comment by sridhar1982** [comment]
I am using gradle version 2.13. both versions are same

**Comment by Hillkorn** [comment]
Hey,
I tried to reproduce it with your setup but the dependency works for me. See  https://github.com/Hillkorn/release-bug/tree/afterRelease

The release will only fail because artifactoryPublish fails cause of misconfiguration but it means that i would be executed. Can you test that it would work for you too? You have to use the afterRelease branch.

Thanks

**Comment by sridhar1982** [comment]
I found the issue. it seems to come from `classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.0"`. I intially picked up the latest buildinfo-extractor and that was causing it.
