### ISSUE TITLE
:checkCommitNeeded fails when gradle-release is configured in an external script

### ISSUE THREAD

**Issue by fabriziofortino** [researchgate/gradle-release#192]
I have an application composed of multiple separate projects. Since I don't like to replicate all the basic configurations on every project I have created a ```my-build``` project that contains some gradle scripts to do common tasks. One of those tasks is the release.

Every project apply the common scripts using the gradle-applyscript-plugin (https://github.com/orctom/gradle-applyscript-plugin).

For example:

    applyscript 'com.acme:my-build:0.1.0/common-tasks.gradle'

If I run ```gradle tasks``` I correctly see the Release tasks.

But when I run ```gradle release``` I get the following error:

```
 gradle release
Changed strategy of configuration ':scripts' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
:release
:svc-masterdata:createScmAdapter
:svc-masterdata:initScmAdapter
:svc-masterdata:checkCommitNeeded
:svc-masterdata:checkUpdateNeeded
:svc-masterdata:unSnapshotVersion
> Building 0% > :release
??> This r> Building 0% > :release > :svc-test:confirmReleaseVersion
:svc-masterdata:confirmReleaseVersion
:svc-masterdata:checkSnapshotDependencies
:svc-masterdata:runBuildTasks
:svc-masterdata:createScmAdapter
:svc-masterdata:initScmAdapter
:svc-masterdata:checkCommitNeeded FAILED
:svc-masterdata:runBuildTasks FAILED
:release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkCommitNeeded'.
> You have uncommitted files:
   M gradle.properties
  
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.201 secs
```

The problem is that I have no uncommitted files. I looked at the code in GitAdapter that checks the status and I have executed the same command in the project home folder (```git status --porcelain```) and it does not return any output.

Another minor problem is that when the plugin prompts for user inputs the text gets truncated.

Any idea?
Thanks

**Comment by fabriziofortino** [comment]
I tried to the debug it and the problem seems to be related to the fact that the task runs multiple times (this is even visible from the output posted in the first message).

Basically, after the SNAPSHOT suffix is removed the task is run again and the checkCommitNeeded fails.

This was actually caused by the applyscript  plugin. I have changed the way to call external scripts using this solution http://stackoverflow.com/a/9590493/1026224 and it works now.

The problem with the truncated texts still remain but it's not blocking.

**Comment by tomasbjerre** [comment]
I'm still seeing this issue. Do you have a working example?

https://github.com/tomasbjerre/violations-lib/blob/feature/checkCommitNeeded-fails/build.gradle

**Comment by tomasbjerre** [comment]
I opened #237 to get some attention on this.

**Comment by tomasbjerre** [comment]
I was applying the script in `afterEvaluate`. Moving it out of there, and just applying it like any other script, resolved my issue.
