### ISSUE TITLE
Push release version to another branch

### ISSUE THREAD

**Issue by tanmaybinaykiya** [researchgate/gradle-release#195]
Feature request: There should be a provision to push release version to another branch. Something on the lines of `pushReleaseVersionBranch` property.
I am not sure, if this is a use case for everyone, but would love to have this.
If this is possible by some other way, please let me know.

**Comment by Hillkorn** [comment]
Do you mean a flow like a dev branch and release branch and the same state the tag is created of should be pushed to the release branch?

**Comment by tanmaybinaykiya** [comment]
Yes, that is correct.

**Comment by gordontyler** [comment]
I'm looking for this as well. In addition, if this method is used, the plugin should not push the commit with the release version on master. The only push to master should be after the version has been updated to the next snapshot. This is to prevent trigger CI builds from master with a non-snapshot version.

**Comment by christopherfrieler** [comment]
Hi,

I was also facing this problem: I want to perform the release on some branch and additionally push the new tag to the master-branch of my git-repo, all done by jenkins.

After some struggle (I'm quite new to gradle and groovy) I found the following workaround, that worked for me. In my build.gradle I extended the createReleaseTag task to export the version and tag into a file:
```
createReleaseTag.doFirst {
    ext.releaseInfo = new File("build/release.info")
    releaseInfo.text = 'release.version=' + project.version + "\n"
    // we should not reimplement the tag-name creation of the release-plugin, but unfortunately the tagName()-method is
    // not available here.
    def params = [ "version": project.version, "name": project.name ]
    def tagName = new SimpleTemplateEngine().createTemplate(release.tagTemplate).make(params).toString()
    releaseInfo.text += 'release.tag=' + tagName + "\n"
}
```
Of course, it would be nice to use the tagName() of the plugin; maybe you can provide it in a future version.

Finally in the jenkins-job I use a build step "inject environment variables" to have these properties available for further build-steps, that perform the merge, deploy on a testing-environment and so on.

**Comment by kmandeville** [comment]
We have been looking for this type of functionality as well. I didn't think it would have been such a special request. I assumed most people build this way (master branch, then merge to a release branch when ready and build releases from there). But I have been unable to find a good working plugin that does this for us. The Axion plugin tried but always seemed to fail

**Comment by Hillkorn** [comment]
Released with 2.8.0

**Comment by danieldietrich** [comment]
Hi @Hillkorn, could you please give an estimation when 2.8.0 will be publicly available?
Thx!

**Comment by Hillkorn** [comment]
Ah I may forgot to make it public in bintray. Will do it in the next hours.
Sorry.
But it is already created and uploaded.
