### ISSUE TITLE
Plugin does not push to the correct git repository in a repo environment

### ISSUE THREAD

**Issue by Satarus** [researchgate/gradle-release#200]
Our project setup is done with google repo and it looks like this

main
|
|-- module
| |--.git
| |-- build.gradle
|
| -- module1
| |-- build.gradle
| | -- sub-module
| |--.git
| |-- build.gradle (Use release plugin here)
|- build.gradle (Use release plugin here)

And I want to be able to release "module1:sub-module" and main. But they should use their respective git repositories. Until now the release plugin only commits and pushes to the main git repository instead of the sub-repository.

I created a pull-request with a possible solution #199

**Comment by Hillkorn** [comment]
Thank you for the pr. I will take a look at it these days. At the moment im sick but will check and reply about the pr if necessary.

**Comment by Satarus** [comment]
Oh so get well soon the pull-request is not going anywhere ;)
