### ISSUE TITLE
Left shift task configuration is deprecated

### ISSUE THREAD

**Issue by kenzierocks** [researchgate/gradle-release#203]
Running this plugin in Gradle 3.2 will warn that `Task.leftShift(Closure)` is deprecated. It won't be removed for a while, but it would be nice to clean up the warning. `<<` is used in [`ReleasePlugin.groovy`](https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/ReleasePlugin.groovy#L61-L74) a lot, so I just thought I'd make an issue to track the switch in-case you hadn't noticed.

**Comment by Hillkorn** [comment]
Yes, will be supported until 5.0 as i know but of course we shouldn't wait that long

**Comment by DPUkyle** [comment]
I'm happy to take this on

**Comment by Hillkorn** [comment]
Hey, thanks that you want to fix it but i think it already is. See https://github.com/researchgate/gradle-release/pull/204
