### ISSUE TITLE
Option to sign tags

### ISSUE THREAD

**Issue by kenzierocks** [researchgate/gradle-release#207]
I'd like the ability to turn on the `-s` option for `git tag`, so that I can sign the generated tag.

**Comment by kenzierocks** [comment]
Hi, it looks like you cut 2.5.0 at the wrong spot and it doesn't include the signing changes. Would you mind making another release?

**Comment by Hillkorn** [comment]
I only created the github releases a bit later but 2.5.0 was already created and published. Will do 2.6.0

**Comment by kenzierocks** [comment]
Thank you!
