### ISSUE TITLE
afterUpdateVersion hook

### ISSUE THREAD

**Issue by martinlechner1** [researchgate/gradle-release#210]
Would you accept a Pull Request containing an afterUpdateVersion hook similar to beforeReleaseBuild, afterReleaseBuild?
I need to run some script with the new version in a subproject and the changed files should ideally be included in the final commit.

**Comment by Hillkorn** [comment]
Why don't you use the dependsOn functionality of gradle to do so?
For example
commitNewVersion.dependsOn runScriptsTask

**Comment by martinlechner1** [comment]
Thanks, wasn't aware of that.

**Comment by martinlechner1** [comment]
Using your proposed solution the version is not carried over to this task. Any ideas why? I am spawning a sub project task in the form:
commitNewVersion.dependsOn ':subProj:taskA'

when looking over updateVersionProperty it seems that it should be working that the new version carries over.

**Comment by Hillkorn** [comment]
Okay the problem is that you assign it at configuration time with and the version is in a list but please try
args = ['version', project.version]

**Comment by martinlechner1** [comment]
Then why would afterReleaseBuild.dependsOn ':subproject:update_npm_project_release_version'
work correctly?

**Comment by Hillkorn** [comment]
because we overwrite the startParameter before we run the configured build tasks. Look here https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/ReleasePlugin.groovy#L78
I haven't tests it but overwriting them again after the version change to snapshot could also work but i haven't tested it.

**Comment by martinlechner1** [comment]
Thanks a lot for your help, the doFirst block indeed solves the problem. I was not aware of when what context is evaluated. This is now clear to me.

**Comment by Hillkorn** [comment]
I'm glad to help out

Martin Lechner <notifications@github.com> schrieb am Mi., 15. Feb. 2017,
23:49:
