### ISSUE TITLE
Wrong version in tag if tagTemplate is set to "v${version}"

### ISSUE THREAD

**Issue by Hillkorn** [researchgate/gradle-release#211]
The created tag will be the snapshot version.

**Comment by Hillkorn** [comment]
workaround for that problem.

```
createReleaseTag {
    doFirst {
        project.release.tagTemplate = "v${version}"
    }
}
```

**Comment by swpalmer** [comment]
As the documentation states:  "Always ensure to use single-quotes, otherwise `$` is interpreted already in your build script"

**Comment by alan-czajkowski** [comment]
@Hillkorn this is not a bug, as @swpalmer stated, you are incorrectly setting the tagTemplate, read the documentation carefully and use single quotes instead

**Comment by Hillkorn** [comment]
Thx
