### ISSUE TITLE
Task.leftShift(Closure) method has been deprecated

### ISSUE THREAD

**Issue by shenliuyang** [researchgate/gradle-release#214]
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

**Comment by Hillkorn** [comment]
Which version do you use?

**Comment by shenliuyang** [comment]
gradle version is 3.4
release plugin version is 2.4.0

**Comment by Hillkorn** [comment]
Please upgrade to a higher version because it is fixed since 2.4.1

**Comment by shenliuyang** [comment]
thanks ...

**Comment by rhonyabdullah** [comment]
Sorry, can anybody help me, i know this warning can replaced with doLas{} but how can i achieve that condition if im using task like this ? 

`tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:unchecked" << "-Werror"
}`

**Comment by shenliuyang** [comment]
compilerArgs  looks like a Collection. Try options.compilerArgs.add("xxx")

**Comment by rhonyabdullah** [comment]
Thanks for your fast respon @shenliuyang 
So i task become like this:

`tasks.withType(JavaCompile) { 
  doLast {
   options.compilerArgs.add("-Xlint:unchecked")
   options.compilerArgs.add("-Werror")
  }
 }`

Warning still goes on, i think the root cause not in that task.

> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

**Comment by Hillkorn** [comment]
You should remove the doLast as it will run it if the task is done and this
is too late to change the arguments. Instead you can add it directly inside

tasks.withType(JavaCompile) { options.compilerArgs.add("-Xlint:unchecked")
options.compilerArgs.add("-Werror") }

Should also work.
Which version of release plugin do you use?

Siagian <notifications@github.com> schrieb am Mo., 22. Mai 2017, 05:41:

**Comment by kopax** [comment]
@Hillkorn Where can I found v2.4.1 ? http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.researchgate%22%20AND%20a%3A%22gradle-release%22

**Comment by Hillkorn** [comment]
@kopax It's available via jcenter

**Comment by capitalgerald** [comment]
**Greeting to you members.**
That is just a warning message already mentions a solution: use the doLast method to add actions.

For me it displayed as below:
`The Task.leftshift<Closure> method has been deprecated and is scheduled to be removed in Grable 5.0 . PLease use Task.doLast <Action> instead.`

But it launched the Emulator.

However complained of Old SDK  as below:
```
pkg: /data/local/tmp/android-debug.apk
Failare [INSTALLED_FAILED_OLDER_SDK]
```

Kibirango Gerald
capitalgerald@gmail.com

**Comment by Hillkorn** [comment]
Do you use version 2.6?

**Comment by capitalgerald** [comment]
Yeah, @Hillkorn 

**_The problem was:_** i had set my minSdkVersion to an higher version of 24 instead of a low one like 14 as stated in the library.

`<preference name="android-minSdkVersion" value="14" />`

I got help from this link 
[This Link](https://stackoverflow.com/questions/9093709/installation-error-install-failed-older-sdk)
My thanks to them.

Thanks for your ##concern, ##Quick Response and the ##Mind of Sharing.
