### ISSUE TITLE
configure on demand breaks the build

### ISSUE THREAD

**Issue by arashbi** [researchgate/gradle-release#219]
I have a multiproject build, using this plugin, build file roughly looks like :

```
plugins {
    id 'net.researchgate.release' version '2.6.0'
}
apply plugin: 'maven'

subprojects {
    apply plugin: 'java'
    afterReleaseBuild.dependsOn uploadArchives
     beforeReleaseBuild.dependsOn test
}
```

when I enable configure on demand, it breaks the build. Gradle cannot find the dependencies for the child project. I guess because they are not configured to start with.

**Comment by ForcedInduction** [comment]
@arashbi 
You've only applied the release plugin to your root project, so `afterReleaseBuild` and `beforeReleaseBuild` do not exist on the sub projects. As mentioned in issue https://github.com/researchgate/gradle-release/issues/180, you could try something like this

```groovy
plugins {
    id 'net.researchgate.release' version '2.6.0'
}
apply plugin: 'maven'

release {
    buildTasks = []
}

subprojects {
    apply plugin: 'java'
}

beforeReleaseBuild.dependsOn project.getSubprojects().collect({it.getTasks().getByName("test")})
afterReleaseBuild.dependsOn project.getSubprojects().collect({it.getTasks().getByName("uploadArchives")})
```
