### ISSUE TITLE
[question] Add generated files to release

### ISSUE THREAD

**Issue by tristanlins** [researchgate/gradle-release#222]
I tried to add a generated `pom.xml` to the release.
To do so, I added a `GenerateMavenPom` task as dependency to the `preTagCommit` task, like this:

```groovy
task generatePomFile(type: GenerateMavenPom) {
  destination = project.file('pom.xml')
  pom = publications.example.pom
}

task deletePomFile(type: Delete) {
  delete 'pom.xml'
}

project.task.preTagCommit.dependsOn generatePomFile
project.task.commitNewVersion.dependsOn deletePomFile
```

The problem is, that `preTagCommit` only use `git commit -a -m ...` without `--untracked-files` (`-u`).
https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/GitAdapter.groovy#L128

Is it a possible way to change this behavior?

**Comment by Hillkorn** [comment]
Hey, you want to add that pom.xml to the git tag only? I mean the simplest workaround i can think of it to do some executions on your own in the gradle setup. But the plugin doesn't really support it with some easy config.
`
task addPomXml(type: Exec) {
    commandLine 'git','add','pom.xml'
}

task removePomXml(type: Exec) {...}
`
And do the rest with the depending on these tasks.
For more info how exec works you can look here https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html

**Comment by tristanlins** [comment]
Calling `git add pom.xml` is what I have done as a workaround now.

The funny part, the `deletePomFile` task works without invoking `git rm pom.xml`.
`git commit -a` will not add untracked files (expect when used with `-u`). But it will commit tracked files, that are removed from the filesystem. I'm not sure, if this is a git "glitch" or not

I don't know how the other scm systems handle this.
But after a little thinking, adding `-u` to the `GitAdapter#commit()` method may end up with unexpected behavior. Not everyone have a "correct" `.gitignore` file.
