### ISSUE TITLE
Message: "un-versioned files" -- Unhelpful

### ISSUE THREAD

**Issue by aplatypus** [researchgate/gradle-release#233]
We are attempting to complete a Jenkins release build on an existing project from a branch.

When the use the test build, the process completes successfully.

When we use the gradle-release plugin to get the release to build, it fails with the message:

```
* What went wrong:
Execution failed for task ':checkCommitNeeded'.
> You have 1 un-versioned files.
```

And the usual advice to try `--stacktrace`, etc.

Unfortunately neither `--stacktrace`, `--info`, nor `--debug` offer any clue(s) as to the location, or names for the said `1 un-versioned files`.

- Is there an option to have all un-versioned / all miscreant files printed-out when this error occurs?
- If that's a "No." then I strongly urge that this facility be added.
   - So that the problem is identified in the first instance and resolved.
   - We have spent some time today attempting to identify which file it might be

**Comment by aplatypus** [comment]
Update -- in this one case, we discovered that setting SVN **ignore** on the `.gradle/` folder allowed this project to build.  That took hours to _just guess_.  I definitely feel reporting all errors is a better approach.

**Comment by Hillkorn** [comment]
But the "You have 1 un-versioned files." told you exactly that you have an unversioned file and this means the output it not completly covererd by your vcs settings. You can ignore this by setting "failOnUnversionedFiles" to true. And you should also see which file is not covered.
Like
`
* What went wrong:
Execution failed for task ':projject:checkCommitNeeded'.
> You have unversioned files:
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ?? test.txt
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
