### ISSUE TITLE
Strip "origin/" of branch

### ISSUE THREAD

**Issue by rickbijkerk** [researchgate/gradle-release#236]
I must be missing something obvious i have a jenkins build job which is parameterised. When i select the branch origin/develop for example the plugins tries to push the new version to origin/origin/develop. I have tried setting the pushToRemote param to "" to perhaps strip the origin part but that did not work. Any ideas? below is my configuration

`release {
    failOnSnapshotDependencies = true
    versionPropertyFile = 'version.properties'
    buildTasks = ['assembleRelease']
    failOnCommitNeeded = false
    failOnUnversionedFiles = false
    tagCommitMessage = 'This is an automatically generated tag of: '
    tagTemplate = "release-" + appVersion
    git {
        requireBranch = ''
    }
}`

**Comment by Hillkorn** [comment]
I think the problem is that "origin/develop" is not a local branch. If you checkout a origin branch directly it tells you also that it is "HEAD detached" like "git branch" would also show you
```
hillkorn~/repos/release-bug[git:(HEAD detached at origin/master)]$git branch
* (HEAD detached at origin/master)
  branch_test
  master
```

Usually jenkins does the checkout automatically in the right way with it's SCM plugins. Did you customized it in some way that it's not doing it right?

**Comment by rickbijkerk** [comment]
Ah i see i might have an idea how this happens, in my build job i have an "check out to specific local branch" defined which uses ${branchName} (the selected parameter branch) which of course checks it out to the local branch origin/develop which then is pushed to origin/origin/develop. Let me try somethign and i'll get back to you

**Comment by rickbijkerk** [comment]
I just tried the build job without the "check out to specific local branch" and it failed with the following error: "Failed to push to remote - [][fatal: remote part of refspec is not a valid name in (HEAD detached from 4745df71)
  ]
"
the strange thing is that the checked out branch by jenkins is "refs/remotes/origin/develop"

mm not quite sure what stap to take next, any other ideas?

**Comment by rickbijkerk** [comment]
appearently my jenkins config was off
