### ISSUE TITLE
release.useAutomaticVersion resets to version 0.0.1 each time again

### ISSUE THREAD

**Issue by enschede** [researchgate/gradle-release#242]
Given a situation where gradle.properties contains the following line:

    version=0.0.2-SNAPSHOT

When I do:

    ./gradlew release -Prelease.useAutomaticVersion=true

I would expect the plugin to set the version to 0.0.2 for building a new version and set the version to 0.0.3-SNAPSHOT afterwards.

However, the version is set to 0.0.1 and setting a tag fails because the tag already exists.

Is this a bug of do I do something wrong? I'm using version 2.6.0

**Comment by Hillkorn** [comment]
Should work. I know that the plugin is having trouble with ":" instead of "=" but your version definition should work I think.
I tested it with project and it worked.

**Comment by marschwar** [comment]
@enschede I had the same problem until I realized that I had a version property in my build.gradle. Everything worked as advertised after I removed it.

**Comment by enschede** [comment]
@marschwar Thnx, it was the right solution.
