### ISSUE TITLE
Use a subproject task in buildTasks in Gradle Release plugin

### ISSUE THREAD

**Issue by dmitrysenkovich** [researchgate/gradle-release#245]
I'm configuring Gradle Release plugin `2.6.0` and want to use `buildTasks` as follows (it is in the root `build.gradle`):

    buildTasks = ['clean', 'build', 'subprojectA:artifactoryPublish', 'subprojectB:artifactoryPublish']

in order to publish two jars only.

However, Gradle can't configure the project complaining as follows:

> Task with name 'subprojectA:artifactoryPublish' not found in root
> project 'rootProject'.

How do I do it?

Thank you very much!

**Comment by Hillkorn** [comment]
https://stackoverflow.com/questions/49415566/use-a-subproject-task-in-buildtasks-in-gradle-release-plugin/49422403?noredirect=1#comment85849361_49422403
