### ISSUE TITLE
Allow to ignore some snapshot dependencies

### ISSUE THREAD

**Issue by essobedo** [researchgate/gradle-release#247]
By default when a project has dependencies on SNAPSHOT versions, the plugin fails as expected however it could be interesting in some specific use cases to just ignore some snapshot dependencies even if it could be considered as not a good practice and should be avoided. 

For example, let's say that a project depends for its tests on another project that is meant to be used by tests only. In this particular use case, whenever we release the project, we will need to also release the test project otherwise the plugin will fail which is what we would like to avoid as the test project is not meant to be released.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/researchgate/gradle-release/pull/248

**Comment by Hillkorn** [comment]
Soon. My son is getting another tooth and keeps me quite busy.
Wanted to check the other pull requests too but can create a release before
I merge the others.

Nicolas Filotto <notifications@github.com> schrieb am Fr., 6. Apr. 2018,
10:20:
