### ISSUE TITLE
requireBranch - argument being ignored?

### ISSUE THREAD

**Issue by pabloem** [researchgate/gradle-release#255]
I'm trying to use `-Prelease.git.requireBranch=my-own-branch`, but I keep getting `Current Git branch is "my-own-branch" and not "master".` errors.

Is the `-Prelease.git.requireBranch=my-own-branch` argument supposed to:
1) Override the hardcoded "master" in [GitAdapter.groovy](https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/GitAdapter.groovy#L30) ?
2) Override a `requireBranch` set in `release/git/` in `build.gradle`?

**Comment by Hillkorn** [comment]
It is not used because by setting it via "-P" it is just a project property and does not change build script configurations as I know. To have that kind of behavior it must be implemented to check for the property and use it. You can do that in your build script too by
```
if(project.hasProperty('release.git.requireBranch')) {
   release.git.requireBranch = project.findProperty('release.git.requireBranch') 
}
```
