### ISSUE TITLE
Allow to change the format of the name and the version while building the tag name

### ISSUE THREAD

**Issue by essobedo** [researchgate/gradle-release#260]
I would like to be able to change the format of the project version while building the tag name, indeed I would like to replace the dots by underscore to match with the internal tag naming policy which doesn't seem to be possible with only a tag template.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/researchgate/gradle-release/pull/261

**Comment by essobedo** [comment]
@Hillkorn Hi could you please at least tell me if this issue and the corresponding MR make sense to you? Thx in advance for your feedback.

**Comment by Hillkorn** [comment]
Hey
Both are changeable on their own. If it's not changeable and you need it I
think it makes sense. But I think I can't merge it fast as I'm still in
Parental leave till beginning of September and my son starts to walk mow
(have to watch him the entire day) but I'll do my best.

Nicolas Filotto <notifications@github.com> schrieb am Mi., 30. Mai 2018,
10:59:

**Comment by essobedo** [comment]
@Hillkorn What do you mean by changeable on their own?

**Comment by Hillkorn** [comment]
Oh forgot that it is already possible what you want. Look at the readme
for tagTemplate

Nicolas Filotto <notifications@github.com> schrieb am Fr., 1. Juni 2018,
08:54:

**Comment by essobedo** [comment]
@Hillkorn Indeed I could finally make it work using `tagTemplate = "${project.version.replace('.', '_')}"` so indeed it is not needed even if it seems more than a workaround rather than a real solution
