### ISSUE TITLE
Permission denied (publickey) on checkUpdateNeeded in Jenkins (Java 9)

### ISSUE THREAD

**Issue by Shadow358** [researchgate/gradle-release#270]
I am currently trying to migrate a java 8 project to java 9. 
The only problem I seem to encounter is that when trying to compile in Java 9 and run my deployment job the build fails on 
`gradle release` and particularly the checkUpdateNeeded step.

The error that I get from the Jenkins log is:
```
 :release
 :build-pipeline:createScmAdapter
 :build-pipeline:initScmAdapter
 :build-pipeline:checkCommitNeeded
 :build-pipeline:checkUpdateNeeded
 Running [git, remote, update] produced an error: [Permission denied (publickey).
 fatal: Could not read from remote repository.
 
 Please make sure you have the correct access rights
 and the repository exists.
 error: Could not fetch origin]
 :build-pipeline:checkUpdateNeeded FAILED
 :release FAILED
 Release process failed, reverting back any changes made by Release Plugin.
 
 FAILURE: Build failed with an exception.
 
 * What went wrong:
 Execution failed for task ':build-pipeline:checkUpdateNeeded'.
 > Failed to run [git remote update] - [Fetching origin
   ][Permission denied (publickey).
   fatal: Could not read from remote repository.
   
   Please make sure you have the correct access rights
   and the repository exists.
   error: Could not fetch origin
   ]
 $ ssh-agent -k
 unset SSH_AUTH_SOCK;
 unset SSH_AGENT_PID;
 [ssh-agent] Stopped.
```

When building the project with JDK8 and source/target compatibility 1.8 it works perfectly fine. When I switch to JDK9 or 10 with source/target compatibility 1.9 then it breaks. 

I also added `ssh-add -L` command to the script which outputs my ssh key moments before the gradle release command. Also other git operations are performed before the release step. Its a private bitbucket repository so any operation should require that key and those operations don't fail.

Any ideas? 
Thanks in advance.

**Comment by Hillkorn** [comment]
Will try to reproduce it on my machine. For now I don't have an idea what the reason could be.

**Comment by Shadow358** [comment]
I think I found the problem.
I was using gradle release plugin 2.4.0 with gradle 4.3.1 which was causing the error above with java 9 and 10. 
Switching to gradle release plugin 2.6.0 with gradle 4.10.2 seems to have fixed the issue.

**Comment by Hillkorn** [comment]
Ah okay but the newest in the plugin portal is 2.7.0
