### ISSUE TITLE
ShadowJar not working with newer 'implementation' configuration

### ISSUE THREAD

**Issue by connect2manu** [researchgate/gradle-release#277]
shadowJar task doesn't works when using dependencies with new 'api' or 'implementation' or 'testImplementation' configurations instead of 'compile' or 'testCompile' configuration.

for e.g:

shadowJar task is ineffective when using dependencies like:

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.5'
}

instead of

dependencies {
    compile 'org.apache.commons:commons-lang3:3.5'
}

**Comment by Hillkorn** [comment]
I think you should report that to https://github.com/johnrengelman/shadow where the shadow plugin with its shadowJar task is located.

This here is only about the release plugin.

**Comment by connect2manu** [comment]
D'oh! Posted on wrong window :P 
Thanks for letting me know :)

**Comment by connect2manu** [comment]
Posted on wrong channel. Closing this issue.
