### ISSUE TITLE
Modify build jenkins pipeline to support release

### ISSUE THREAD

**Issue by matteoturra** [researchgate/gradle-release#291]
How can be a build pipeline transformed to support release process?

Normally build pipeline do this stage:
- checkout
- build
- test
- code analysis
- publish

I would like to insert release stages to perform the release : 
- checkout
- __all task of beforeReleaseBuild__
- build
- test
- code analysis
- __createReleaseTag__
- publish _(release)_
- __updateVersion commitNewVersion__

Is it feasible?
Which task of gradle release plugin must be used in the step highlighted?

**Comment by Hillkorn** [comment]
* **all task of beforeReleaseBuild**
* build
* test
* code analysis
Can be replaced with "runBuildTasks

I think the problem would be the version. Do you always want to do minor version upgrades?

**Comment by matteoturra** [comment]
Is this correct?
```
stage("Pre-Release") {
            when {
                expression {
                    params.release
                }
            }
            steps {
                sh './gradlew createScmAdapter initScmAdapter checkCommitNeeded checkUpdateNeeded unSnapshotVersion confirmReleaseVersion checkSnapshotDependencies -Prelease.useAutomaticVersion=true'
            }
}

stage('Build') {}

stage('Test') {}

stage("Code Analysis") {}

stage("Release") {
            when {
                expression {
                    params.release
                }
            }
            steps {
                wrap([$class: 'BuildUser']) {
                    sh "git config user.name '${BUILD_USER_ID}'"
                    sh "git config user.email '${BUILD_USER_EMAIL}'"
                }
                sh './gradlew createScmAdapter initScmAdapter preTagCommit createReleaseTag  updateVersion  commitNewVersion -Prelease.useAutomaticVersion=true'
            }
}

stage("Publish") {}

```

**Comment by Hillkorn** [comment]
Looks okay in general. I'm also facing that problem with the pipelines currently but didn't tackled it yet. A call of release would do everything but I know that the overview in jenkins gets bad as only one stage is visible.

**Comment by Hillkorn** [comment]
> The problem with this approach is then _updateVersion_ task does not put -SNAPSHOT :-(

Right but you can workaround that.

**Comment by Hillkorn** [comment]
I think if you put in your build.gradle
`
release {
    attributes.usesSnapshot = true
}
`
It should always use snapshots versions. I think it makes sense to propagate that as a normal config option.

**Comment by matteoturra** [comment]
Can I put -Prelease.attributes.usesSnapshot=true in the gradle command line?

**Comment by Hillkorn** [comment]
Won't work out of the box. You'll have to read it in your build.gradle on your own like
```
release { attributes.usesSnapshot = project.findProperty('
release.attributes.usesSnapshot') }
```

**Comment by matteoturra** [comment]
Thanks
