### ISSUE TITLE
Failed builds for empty git repositories

### ISSUE THREAD

**Issue by acoburn** [researchgate/gradle-release#295]
I have a project that uses this plugin. When I upgraded from version 2.7.0 to 2.8.0, the gradle build fails immediately in cases where the source code does not have a `./.git` directory, e.g. when someone "downloads" from github rather than cloning the repository. This is also relevant for AWS CodeBuild pipelines, since the code is downloaded rather than cloned in those cases.

It appears that this issue was introduced in this commit: 4e43ac36a70ee5a3bb07a028a688ae2ad05afa44, specifically [this line](https://github.com/researchgate/gradle-release/commit/4e43ac36a70ee5a3bb07a028a688ae2ad05afa44#diff-f30912843a82604298ff3b83a917a3b0R56).

Here is some sample output:

```
$ gradle clean 

> Configure project :
Running [git, branch, --no-color] produced an error: [fatal: not a git repository (or any of the parent directories): .git]
```

The underlying exception is `Caused by: org.gradle.api.GradleException: Error, this repository is empty.`

This occurs with _every_ gradle task (including `clean` as shown above), not just a release-related task. I wouldn't mind if this failed for the `release` task, but failing like this on build-related tasks is a bit of a show-stopper.

This issue is very similar to #286

**Comment by Hillkorn** [comment]
I'll have  to make it lazy.

Thanks for the report.

**Comment by loginet-vfeher** [comment]
Is there any progress with this issue? We are using 2.7.0 of the plugin regarding this bug.
