### ISSUE TITLE
How generate Release candidate or Snapshot version

### ISSUE THREAD

**Issue by vinyoliver** [researchgate/gradle-release#315]
How can I generate a release candidate version or even as a snapshot in a way that won't update the current version? For example, assuming my next version would be 1.0.1 I'd like to be able to generate new versions as following

1.0.1-rc1, 1.0.1-rc2, 1.0.1-rc3 until I finally generate the final version 1.0.1;
or
1.0.1-SNAPSHOT-1, 1.0.1-SNAPSHOT-2... until I finally generate the final version 1.0.1;

**Comment by jvmlet** [comment]
@vinyoliver , have a look at [this ](https://github.com/nebula-plugins/nebula-release-plugin)alternative

**Comment by Hillkorn** [comment]
There is built in support for this. You would need to change the version in the gradle.properties and do a `gradle publish/uploadArchive` run

**Comment by F43nd1r** [comment]
Can't you just set the version back after creating your release candidate? Something like this
```
./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=1.0.1-rc1 -Prelease.newVersion=1.0.1-SNAPSHOT
```
