### ISSUE TITLE
An ability to disable push to remote repo on release

### ISSUE THREAD

**Issue by szpak** [researchgate/gradle-release#33]
It is sometimes useful to have a full control over interaction with remote error on release process. There could be an additional flag (pushChanges? - default true) which would allow to review changes done by a release plugin before (manual) push.

**Comment by mageddo** [comment]
Okay, I spent some minutes to find the option, so if you want to disable automatic git push you can use the option below:

```
release {
  git {
    pushToRemote.set('') // disabling push to remote
  }
}
```
