### ISSUE TITLE
Get the value of "newVersion"

### ISSUE THREAD

**Issue by denodaeus** [researchgate/gradle-release#337]
Is there a way of getting the value of `newVersion` from the gradle build script?  My use case is I want to use the next version committed back to the repository to also update some package.json files with nodejs based libraries in a monorepo.  I see there is code in ReleaseExtension that calls a method getVersionUpdate, but it looks like the actual value of newVersion is private and scoped to a few methods.

Thanks,

**Comment by F43nd1r** [comment]
Something like this should do the trick

```kotlin
tasks.register("GetNewVersion") {
    doLast {
        println("New version is ${project.version}")
    }
}
tasks["updateVersion"].finalizedBy("GetNewVersion")
```

**Comment by denodaeus** [comment]
That does the trick, thanks!
