### ISSUE TITLE
Leading space inserted for title of pre tag commit

### ISSUE THREAD

**Issue by tueda** [researchgate/gradle-release#361]
Somehow `./gradlew release` inserted a leading space to the commit title for `pre tag commit`. This occurred to me with
```
Gradle 7.5
net.researchgate.release 3.0.0

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.14 (Ubuntu 11.0.14+9-Ubuntu-0ubuntu2.20.04)
OS:           Linux 5.10.102.1-microsoft-standard-WSL2 amd64
```
Downgrading the version `3.0.0` to `2.8.1` fixes the issue, i.e., no leading space inserted, see the image below.

![image](https://user-images.githubusercontent.com/1481665/180822250-66b02d16-75bc-4a81-81b7-abdfef1a7acb.png)

I think this must be reproducible if one uses [my repo](https://github.com/tueda/donuts) and runs `./gradlew release`, though it is totally unclear to me why this could happen. It seems that GitHub/GitLab interface ignores such leading spaces in commit titles, so one should use `git log` to see them.

**Comment by peetkes** [comment]
we also ran into this while we setup workflow rules on skipping commits which started with '[Gradle Release Plugin]'. The pre tag  commit slipped through because of the leading space.

**Comment by peetkes** [comment]
That seems a logic explanation. Would it make sense to check if preCommitText if empty before prepending it to the message?
