### ISSUE TITLE
Problem win32 subversion 1.7 

### ISSUE THREAD

**Issue by leoincedo** [researchgate/gradle-release#39]
project is not problem

i was testing from svn 1.6 ( osx ) but problem is windows or subversion 1.7

plz.!!! i want to release plugin

[liongo.SF2-SEONGWOO-PC] → sh gradlew release
>>>>> xxxx Poject <<<<<
0.7.4.1-GR-SNAPSHOT
:release
>>>>> xxxx Poject <<<<<
0.7.4.1-GR-SNAPSHOT
:xxxxserver:initScmPlugin
:xxxxserver:checkCommitNeeded
!!WARNING!! You have 19 un-versioned files.
:xxxxserver:checkUpdateNeeded FAILED
:release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkUpdateNeeded'.
> Running "svn info svn://developer.xxxx.co.kr/svn/xx2/trunk/xxxxserver" produced an error: [svn: E670008: Unable to connect to a repository at URL 'svn://developer.xxxx.co.kr/svn/xx2/trunk/xxxxserver'
svn: E670008: Unknown hostname 'developer.xxxx.co.kr']

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.721 secs

[liongo.SF2-SEONGWOO-PC] → svn info svn://developer.xxxxx.co.kr/svn/xx2/trunk/xxxxserver
Path: xxxxserver
URL: svn://developer.xxxx.co.kr/svn/xx2/trunk/xxxxserver
Repository Root: svn://developer.xxxxx.co.kr/svn/xx2
Repository UUID: e7335162-918b-11e0-b175-019f8cb6028d
Revision: 3418
Node Kind: directory
Last Changed Author: liongo
Last Changed Rev: 3418
Last Changed Date: 2013-06-03 20:12:59 +0900 (, 03 6 2013)

**Comment by danez** [comment]
Fixed by #68
