### ISSUE TITLE
Tag Commit Message flag for CI CD

### ISSUE THREAD

**Issue by uPagge** [researchgate/gradle-release#391]
Hello. I'm trying to use the `-Prelease.tagCommitMessage` flag when building from Gitlab CICD and it doesn't work for me. Should this flag work or is it not supported?

**Comment by Hillkorn** [comment]
It's not supported but you can configure it like this on your own if you want to.
```
release.tagCommitMessage = project.findProperty('release.tagCommitMessage')
```
