### ISSUE TITLE
Release version and new version as build paremeters

### ISSUE THREAD

**Issue by tlempart** [researchgate/gradle-release#44]
Hi,

   I want to create releases on jenkins with help of release plugin (https://wiki.jenkins-ci.org/display/JENKINS/Release+Plugin) where user can self specify release version and new version. It would be great, if I could call gradle in such way:
```gradle release -PreleaseVersion='1.0.0' -PnewVersion='1.1.0-SNAPSHOT'```

**Comment by danez** [comment]
Version 1.3 will be released very soon.
