### ISSUE TITLE
Tag created from wrong revision in svn

### ISSUE THREAD

**Issue by smurfs** [researchgate/gradle-release#48]
Hi 
I tried this plugin and it updated the gradle.properties with the updated version and also created the release tag . But, once the version is updated in the gradle.properties, it does not commit that code to svn. 
Can anyone please let me know, if i have missed something. Or how to implement that.
Thanks
Smurf

**Comment by danez** [comment]
This is fixed with https://github.com/researchgate/gradle-release/commit/d9ffcb326fd7d922d705ab25454d1b6e5abdfe8e and will be released in 1.3
