### ISSUE TITLE
A failed release only checks if gradle.properties exists even if a custom properties file is used

### ISSUE THREAD

**Issue by jeffastorey** [researchgate/gradle-release#57]
The check for reverting a failed release looks like:

    if (releaseConvention().revertOnFail && project.file("gradle.properties")?.exists()) {
         log.error("Release process failed, reverting back any changes made by Release Plugin.")
        this.scmPlugin.revert()
    } else {
        log.error("Release process failed, please remember to revert any uncommitted changes made by the Release Plugin.")
    }

If a custom properties file is being used, the check should be for that file

**Comment by danez** [comment]
As far as I see fixed, but not released. Closing as 1.3 to be released soon
