### ISSUE TITLE
Problems with --parallel

### ISSUE THREAD

**Issue by tschulte** [researchgate/gradle-release#60]
When using --parallel, the release will not work reliably. I have parallel mode enabled in my ~/.gradle/gradle.properties.

Workaround:
add a line 'tasks.release.startParameter.parallelThreadCount = 0' in your buildscript

I see two possible sollutions:

1.: in ReleasPlugin.groovy set startParameter.parallelThreadCount = 0 in definition of the release task
2.: use Task.mustRunAfter for each task.

**Comment by danez** [comment]
This is fixed in the upcoming 3.0 version.
