### ISSUE TITLE
Git: Configuration requireBranch and push

### ISSUE THREAD

**Issue by tschulte** [researchgate/gradle-release#61]
If I configure requireBranch to null or '' ('' is only a problem on master, not in Version 1.2), only master will be pushed ('git push origin master' is called). Only if I also set pushToCurrentBranch to true, the current branch is pushed.

**Comment by ddrozdov** [comment]
Any news here?
There is still an issue in the latest version.

pushToCurrentBranch seems to help, please document it at least.

**Comment by danez** [comment]
This will be fixed in 2.3.0. The option ```pushToCurrentBranch``` will be deprecated, as it will be the default behavior.
So in future setting requireBranch to some false-ish value is enough.
