### ISSUE TITLE
Next version doesn't have -SNAPSHOT even if previous one had

### ISSUE THREAD

**Issue by kutzi** [researchgate/gradle-release#64]
I'm using version 1.2 of the plugin with  -Pgradle.release.useAutomaticVersion=true 

I have a gradle.properties file as part of the project.
Previous to the release the version in in was:
version=1.0.0-SNAPSHOT

The the plugin created the pre-tag commit:
[Gradle Release Plugin] - pre tag commit:  '1.0.0'.
So far so good

But afterwards it increased the version to 
[Gradle Release Plugin] - new version commit:  '1.0.1'.)

I'd expect to have a 1.0.1-SNAPSHOT version afterwards

**Comment by danez** [comment]
If anyone can reproduce please reopen with a hint/example.
