### ISSUE TITLE
release for multi project

### ISSUE THREAD

**Issue by michaeldienderchampiondata** [researchgate/gradle-release#66]
Hi,

I have a multi-project build. the parent gradle.properties has the version value as 1.0.0-SNAPSHOT.

sub-project 2 has a dependency on sub-project 1. e.g. project(':sub-project1')

when I run the release task. It fails with Project contains SNAPSHOT dependencies: sub-project1:1.0.0-SNAPSHOT.

Is there a solution to this?

**Comment by danez** [comment]
tracked in #144
