### ISSUE TITLE
Release process stuck to createReleaseTag task

### ISSUE THREAD

**Issue by tbouron** [researchgate/gradle-release#77]
Hi there. I'm trying to setup you release plugin but the whole process is stuck to:
-  "preTagCommit" in a case of "gradle clean release"
-  "createReleaseTag" in a case of "gradle release"

Point to notice is that the gradle.properties (version changed from x.x.x-SNAPSHOT to x.x.x) is committed into my local repository.

Did you ever encounter this issue?

I'm running gradle 1.10 and git 1.8.3

Thanks! :)

**Comment by smohamali** [comment]
You need to store the credentials, try using https://git-scm.com/docs/git-credential-store
