### ISSUE TITLE
Issues with Gradle 2.0 and maven-publish plugin

### ISSUE THREAD

**Issue by durmuse** [researchgate/gradle-release#82]
The plugin doesn't play well with the new maven-publish plugin. 
Everything was working fine until we switched to Gradle 2.0 and maven-publish plugin.

Publishing to artifactory is now failing for us because the release plugin is looking for SNAPSHOT artifacts for some reason.

**Comment by danez** [comment]
with version 2.1.0 this should now work as expected when using the gradle dependsOn mechanism. If not please reopen.
