### ISSUE TITLE
Plugin fails in commitCheckNeeded after modifying gradle.

### ISSUE THREAD

**Issue by TrueDub** [researchgate/gradle-release#83]
Whenever I execute the plugin, the initScmPlugin phase modifies gradle.properties, causing the commitCheckNeeded phase to fail saying there are uncommitted files.

I've verified this by running the individual tasks - the files are modified, although the contents are identical.

Has anyone seen this behaviour before, and if so is there a fix?

**Comment by felixbarny** [comment]
I have the same issue on Mac, but not on Windows :confused:
Do you have any workaround?

**Comment by nigelcharman** [comment]
I'm also seeing this on https://github.com/concordion/concordion-collapse-output-extension. I've added the failOnCommitNeeded=false workaround to make it work, but would rather not have this set.

The strange thing is, an identical build has been working fine for other projects. I've upgraded to 2.0.1 and am still seeing the issue.

Did anyone find a fix?

**Comment by danez** [comment]
I would be nice to know what the initScmPlugin tasks is exactly changing. The only two things I could think of is either line endings or the file encoding.

**Comment by nigelcharman** [comment]
You pointed me in the right direction, but it was neither of those two :smiley: 

I found that gradle.properties had the execute bit set (file mode 100755). Running `chmod a-x gradle.properties` then committing and pushing gradle.properties fixed it for me.
