### ISSUE TITLE
Release Does Not Honor -PnewVersion Parameter

### ISSUE THREAD

**Issue by ruifilipevarela** [researchgate/gradle-release#85]
as gradlew release -Pgradle.release.useAutomaticVersion=true -PreleaseVersion=0.6.0 -PnewVersion=0.7.0-SNAPSHOT

the release does not use the releaseVersion and newVersion properties on the process, and always increments the value defined on the gradle.properties

**Comment by glureau** [comment]
Same issue here.
@ruifilipevarela : Have you finally find some workaround?

**Comment by danez** [comment]
Which versions are you using, probably 1.2 which does not yet include this feature. Please wait for 1.3 to be released soon.
