### ISSUE TITLE
SVN problem due to localized executions

### ISSUE THREAD

**Issue by hcastillo** [researchgate/gradle-release#86]
Even in src/main/groovy/release/SvnReleasePlugin.groovy it tries to extract the current revision number with LC_COLLATE=C, it fails in Spanish because with that environment "svn" still returns Spanish translation and the regular expression for obtain the revision fails "Revisión: 12345" !~ ~/Revision:\s(.*?)$/

I suggest to use LANG=C instead of LC_COLLATE.

In my case, it was enough to change the previous pattern  in src/main/groovy/release/SvnReleasePlugin.groovy to match with "Revisión", but this could fail also with another versions of "svn".

Checked with svn 1.8.10 and 1.7.18.

**Comment by danez** [comment]
Should be fixed by https://github.com/researchgate/gradle-release/commit/036a8788d17001cf50ac534a98664092ae3197b5
