### ISSUE TITLE
failOnUpdateNeeded ignored

### ISSUE THREAD

**Issue by ibalashov** [researchgate/gradle-release#87]
I wonder if this plugin works at all with Mercurial. The reason of the doubt is that `hg in -q` never returns zero (which is intended behaviour in `hg`). The above cases `checkUpdateNeeded` to fail, even with `failOnUpdateNeeded` set to `false`

    gradle clean release --debug -Pgradle.release.failOnUpdateNeeded=false
    :hello-world:checkUpdateNeeded FAILED

     Running "hg in -q" produced an error: [warning: hg.mycompany.com certificate with fingerprint ee:dc:62:7e:11:ea:15:cb:19:29:b2:8d:cc:aa:5b:4b:b7:01:df:27 not verified (check hostfingerprints or web.cacerts config setting)

**Comment by danez** [comment]
This should be fixed when I look at the current code. `failOnStderr` is now set to `false`
