### ISSUE TITLE
Cannot run program "pwd" on Windows

### ISSUE THREAD

**Issue by SanderDN** [researchgate/gradle-release#90]
I'm getting the following error when running the release task on windows, using GIT:

> Cannot run program "pwd" (in directory "D:\dev\playground\conflictortwo"): CreateProcess error=2, The system cannot find the file specified

When trying this on cygwin (linux emulator), everything seems to work properly.

**Comment by danez** [comment]
Sorry that debug statement slipped in. Fixed in 2.0.1
