### ISSUE TITLE
Add support for SVNKit

### ISSUE THREAD

**Issue by mwhipple** [researchgate/gradle-release#93]
This is captured in a code comment but there is no issue floating around that I can see. The existing CLI svn can cause issues in a CI system.

I should be able to work on this but want to make sure I'm not doing anything undesired and the solution can adapt to solve any known problems beyond the ones I'm facing.

My initial thinking is to develop the SvnKit support in a separate project or subproject and then modify the ReleasePlugin to do a simple lookup of the ScmPlugin rather than referencing the types themselves (such as a map in ReleasePluginConvention).  The end should be that the core remains logically unchanged but a user would be able to do something like `release { scmPlugins.svn = SvnKitReleasePlugin}` and then also have a simple extension point if SCM behavior has to be further tweaked.

**Comment by danez** [comment]
What are the problems which you are facing? In general it would be a great improvement to have a structure that would allow different "adapters" to be added. But haven't thought about that yet.

**Comment by mwhipple** [comment]
Mostly just nuisance problems rather than anything that is really disruptive.
The immediate issue seems to be that the Jenkins job just hangs when it would be prompting for the creds for CLI svn and I don't have shell access or an immediate way to store/cache them.
I also ran into portability issues a year or so ago also for which I don't remember details: most likely with front end developers on the team running Windows and not having the svn command ready on their path.

**Comment by mwhipple** [comment]
I've started an SvnKit based plugin that should be passably usable in the next day or two and then subsequently refined and cleaned up (after which I could shuffle it around to be integrated into the main plugin if desired): https://github.com/mwhipple/gradle-release-svnkit/blob/master/src/main/groovy/com/mattwhipple/release/SvnKitReleasePlugin.groovy. If the core release plugin is made extensible it should be able to plug itself in or be explicitly configured by users (I submitted a PR to support the subclassing approach I'm presently using in that project).
