### ISSUE TITLE
tagPrefix always with "-" behind

### ISSUE THREAD

**Issue by lihanyu23** [researchgate/gradle-release#97]
I'd like to simply add "v" before the version name to make the tag name the same as maven-release-plugin. For example, v1.0.0.

But since here in PluginHelper.groovy:
String prefix = releaseConvention().tagPrefix ? "${releaseConvention().tagPrefix}-" : (releaseConvention().includeProjectNameInTag ? "${project.rootProject.name}-" : "")

There will be automatically "-" added behind the tagPrefix property.
Won't it be cool to let people add "-" themselves in the tagPrefix instead of adding it for them ?

**Comment by danez** [comment]
This issue is being discussed in the PR #89 and #96

**Comment by lihanyu23** [comment]
I didn't see that, thanks !
