### ISSUE TITLE
Applying plugin to project without SCM fails the build

### ISSUE THREAD

**Issue by devkiela** [researchgate/gradle-release#99]
Hi,

in my opinion it would be nice if the plugin wouldn't fail the build by just applying it to a project not under SCM (yet) but when running a related task.

FAILURE: Build failed with an exception.

* What went wrong:
An exception occurred applying plugin request [id: 'net.researchgate.release', version: '2.0.2']
> Failed to apply plugin [id 'net.researchgate.release']
   > Unsupported SCM system, no .svn, .bzr, .git, or .hg found in [<Dir>] or its parent directories.

**Comment by danez** [comment]
This is fixed with commit f9b8bcd28fbfea6bb6f44b4aba53482362588e3b and will be released with version 2.1
